# Missing data


```{r, echo=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
## Load libraries
library(here)
library(tidyverse)
library(Hmisc)
library(naniar) ## for missing data 
library(gt)
library(kableExtra)
library(DT)
load(here::here("data", "a_bact.rda"))
```


## Per variable missingness

Number and percentage of missing. 

```{r, message =FALSE, warning =FALSE , echo=FALSE}
a_bact %>%
  select(-ID, -BloodCulture, -BC) %>%
  miss_var_summary() %>%
  gt::gt() %>%
    gt::cols_label(
    variable = md("**Variable**"),
    n_miss = md("**Missing (count)**"),
    pct_miss = md("**Missing (%)**")
  ) %>%
  gt::fmt_number(
    columns = vars(pct_miss),
    decimals = 2
  )

```


```{r, message =FALSE, warning =FALSE , echo=FALSE}
a_bact %>%
  select(-ID, -BloodCulture, -BC) %>%
  gg_miss_var(show_pct = TRUE)
```



## Missingness patterns over variables


```{r, message =FALSE, warning =FALSE , echo=FALSE}
a_bact %>%
  select(-ID, -BloodCulture, -BC) %>%
  naniar::vis_miss(sort_miss = TRUE, show_perc_col = TRUE) 
```

```{r, message =FALSE, warning =FALSE , echo=FALSE}
a_bact %>%
  select(-ID, -BloodCulture, -BC) %>%
  gg_miss_case()
```


```{r, message =FALSE, warning =FALSE , echo=FALSE}
a_bact %>%
  select(-ID, -BloodCulture, -BC) %>%
  gg_miss_upset()
```




## (In)complete cases

This section presents patients with a least one missing value. First we list out patients with at least one missing value in a filterable table. 

```{r, message =FALSE, warning =FALSE , echo=FALSE}
cc <-
  a_bact %>%  
  select(-ID, -BloodCulture, -BC) %>% 
  filter(!complete.cases(.))

DT::datatable(cc)
```

Then we report the pattern of missing for this set of patients. 

```{r, message =FALSE, warning =FALSE , echo=FALSE}
cc %>% gg_miss_upset()
```



## Section session info

```{r, message =FALSE, warning =FALSE , echo=FALSE}
sessionInfo()
```
