--- 
title: "Regression without regrets"
subtitle: "Workflow of initial data analyses"
author: "TODO: Compelte author list"
date: "`r Sys.Date()`"
knit: "rmarkdown::render_site"
site: bookdown::bookdown_site
output:
  rmdformats::readthedown:
    thumbnails: false
    lightbox: false
    gallery: TRUE
    highlight: tango
    use_bookdown: TRUE
    toc_depth: 2
    fig_caption: false
    code_folding: hide
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: bailliem/ida-regression-private
description: "The focus of this document/website is to provide guidance on conducting initial data analysis in a reproducible manner in the context of intended regression analyses."
---


# Regression without regrets: Workflow of initial data analyses {-}

# Overview

```{r include = FALSE}
#source("common.R")
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
library(Hmisc)
knitrSet(lang = 'markdown', fig.path = 'figure/')
library(tidyverse)
library(here)
source(here::here("R", "ida_plot_univar.R"))
```


The focus of this document/website is to provide guidance on conducting initial data analysis in a reproducible manner in the context of intended regression analyses.

TODO: to add. create ToC dynamically:



```{r eval=FALSE}
install.packages("bookdown")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
