
#  Bivariate distributions

Multivariate a_crash2

This code is a continous by example

```{r, echo = FALSE, message = FALSE, warning = FALSE }
library(here)
library(tidyverse)
library(janitor)
library(summarytools)
library(Hmisc)
library(arsenal)
```

## Read data 

### Load the dataset.

```{r, message = FALSE}
load(here::here("data", "a_crash2.rda"))

## TODO: Move out to data prep
## TODO: Complete metadata by adding missing labels. 
## This should be a dervived dataset stored in data as we are adding to the oirginal source dataset obtained. 
a_crash2 <- Hmisc::upData(a_crash2,
               labels = c(age = 'Age'),
               units = c(age = "years", injurytime = "hours", gcs = "points"))

```



### Summary 

```{r, results="asis"}
library(arsenal)
crs.char <-
  tableby(
    sex ~ age + hr + rr + sbp ,
    data = a_crash2,
    test = FALSE,
    numeric.stats = c("median", "q1q3", "range"), 
    digits = 1, digits.p = 2, digits.pct = 1
  )

summary(crs.char, title = 'Patient characteristics') 
```

```{r}
library(gtsummary)

a_crash2 %>%
  select(sex, age, hr, rr, sbp) %>%
  gtsummary::tbl_summary(by = "sex") %>%
  bold_labels()

```



### Histograms

```{r, echo = FALSE, message = FALSE}
a_crash2 %>%
  filter(!(is.na(sex))) %>%
  with(., histboxp(
    x = age,
    group = sex,
    sd = TRUE,
    bins = 200
  ))

```



## Age 

### Continous 

```{r}

a_crash2 %>% dplyr::filter(!is.na(sbp)) %>% tally()
a_crash2 %>% dplyr::filter(is.na(sbp)) %>% tally()

bigN <- a_crash2 %>% dplyr::filter(!is.na(sbp) & !is.na(age)) %>% tally()
n_miss <- a_crash2 %>% dplyr::filter(is.na(sbp) | is.na(age)) %>% tally()

title <-
  paste0("Plot of ", Hmisc::label(a_crash2$age), " and ", Hmisc::label(a_crash2$sbp))

caption <-
  paste0(
    "n = ",
    bigN,
    " subjects displayed.\n",
    n_miss,
    " subjects with a missing value in at least one of the variables."
  )


x_axis <- paste0(Hmisc::label(a_crash2$age), " [", Hmisc::units(a_crash2$age), "]")
y_axis <- paste0(Hmisc::label(a_crash2$sbp), " [", Hmisc::units(a_crash2$sbp), "]")


p1 <- a_crash2 %>%
  dplyr::filter(!is.na(sbp) & !is.na(age)) %>%
  mutate(sbp = as.numeric(sbp), 
         age = as.numeric(age)) %>%
  ggplot(aes(x = sbp, y = age)) +
  ylab(x_axis) +
  xlab(y_axis) +
  labs(
    title = title,
    caption = caption
  ) +
  geom_point(shape = 16, #size = 0.5,
             alpha = 0.5,
             color = "firebrick2") +
  geom_rug() +
  theme_minimal()

p1

```

### Continous2

```{r}
p1 <- a_crash2 %>%
  filter(!is.na(sbp) & !is.na(age)) %>%
  mutate(sbp = as.numeric(sbp), 
         age = as.numeric(age)) %>%
  ggplot(aes(x = sbp, y = age)) +
  geom_point(shape = 16, size = 0.5,
             alpha = 0.5,
             color = "firebrick2") +
  geom_rug() +
  theme_minimal()

p2 <- a_crash2 %>%
  filter(!is.na(sbp) & !is.na(hr)) %>%
  mutate(sbp = as.numeric(sbp), 
         age = as.numeric(hr)) %>%
  ggplot(aes(x = sbp, y = hr)) +
  geom_point(shape = 16, size = 0.5,
             alpha = 0.5,
             color = "firebrick2") +
  geom_rug() +
  theme_minimal()


p3 <- a_crash2 %>%
  filter(!is.na(sbp) & !is.na(rr)) %>%
  mutate(sbp = as.numeric(sbp), 
         age = as.numeric(rr)) %>%
  ggplot(aes(x = sbp, y = rr)) +
  geom_point(shape = 16, size = 0.5,
             alpha = 0.5,
             color = "firebrick2") +
  geom_rug() +
  theme_minimal()


p4 <- a_crash2 %>%
  filter(!is.na(hr) & !is.na(age)) %>%
  mutate(sbp = as.numeric(hr), 
         age = as.numeric(age)) %>%
  ggplot(aes(x = hr, y = age)) +
  geom_point(shape = 16, size = 0.5,
             alpha = 0.5,
             color = "firebrick2") +
  geom_rug() +
  theme_minimal()

```


### Continous3 

```{r}

library(patchwork)
(p1 + p2 ) / (p3 + p4)
```





## Session info

```{r}
sessionInfo()
```
