# SAP nhanes

## Data set 

The National Health and Nutrition Examination Survey (NHANES) is a program of studies designed to assess the health and nutritional status of adults and children in the United States. The survey examines a nationally representative sample of about 5,000 persons each year. [Link to CDC  NHANES website](https://www.cdc.gov/nchs/nhanes/about_nhanes.htm)

The NHANES study contains objectively measured physical activity data collected using hip-worn accelerometers from multiple cohorts. High quality processed activity data combined with mortality and demographic information can be downloaded and used in R with code from Andrew Leroux (https://andrew-leroux.github.io/rnhanesdata/articles).


Here, we look at the subset of participants between 50 and 85 years old from the 2003-2004 and 2005-2006 samples (n=2978) who wore a hip-worn accelerometer in the free living environment for up to 7 days.   The response ID is seqn.

### Sociodemographic variables 

* age at examination [years] (i.e. when participants wore the device), age
* gender (male and female), gender
* race/ethnicity (non-Hispanic white, non-Hispanic black, Mexican American, and other) 
* education (< high school graduate, high school graduate/general educational development [GED], some college, and college graduate), educationadult
* 5 year mortality,  NAs for individuals with follow up less than 5 years and alive, yr5.mort 
* Person Months of Follow-up from MEC/Exam Date, permth.exm (follow-up time in this cohort in years = permth.exm/12) 
* final mortality status, mortstat

### Health and behavior variables 

* smoking status (current smoker, former smoker [those reporting quitting within the previous 6 months], and nonsmoker), smokecigs
* alcohol consumption, drinkstatus
* BMI, bmi
* obesity, bmi.cat
* diabetes, diabetes
* congestive heart failure, chf
* cancer, cancer
* stroke, stroke
* average systolic blood pressure using the 4 measurements per participant, sys , 
* Total cholesterol (mg/dL), lbxtc 
* HDL cholesterol, lbdhdd  
* mobilityproblem ("No Difficulty","Any Difficulty")

### Physical activity data

* total activity counts per day (TAC/d)
* total log activity count (TLAC)
* total minutes of moderate/vigorous physical activity (MVPA)
* total accelerometer wear time (WT)
* sedentary/sleep/non-wear to active transition probability (SATP)
* active to sedentary/sleep/non-wear transition probability (ASTP): Bout length was defined as the number of consecutive minutes spent in either an active or sedentary state and a daily activity profile was created for each participant to detect alternating bouts of sedentary and active states. ASTP was defined as the probability of transitioning from an active to a sedentary state and calculated as the reciprocal of the average active bout duration. ASTP was calculated for each day and averaged across valid days to derive a single measure of ASTP for each participant. 

In addition, there are total log activity count summary measures (tlac.1, tlac.2, …, tlac.12) in each 2-hr window, i.e. 12AM-2AM, 2AM-4AM, 4AM-6AM, etc. 

