# Univariate summary CRASH-2 dataset 

```{r,message = FALSE, warning = FALSE }
library(here)
library(tidyverse)
library(janitor)
library(summarytools)
library(Hmisc)
```

## Read data

### Load the dataset.

```{r load_crash2, message = FALSE}
load(here::here("data", "crash2.rda"))
```

### Describe the dataset

Use Hmisc describe function. 

```{r desc_crash2, message = FALSE, results='asis', warning=FALSE}
crash2 %>%
  Hmisc::describe(descript = "MY DATA SET TITLE") %>%
  Hmisc::html()
```







```{r}
# crash2 %>%
#   dplyr::select(age, injurytime, sbp, rr, cc) %>%
#   gtsummary::tbl_summary(
#     # split table by treatment variable
#     #by = trt,
#     # change variable labels
# #    label = list(marker ~ "Marker, ng/mL",
# #                 stage ~ "Clinical T Stage"),
#     # change statistics printed in table
#     statistic = list(
#       all_continuous() ~ "{mean} ({sd}) / ({min}, {max}) / {median} / {p5} {p25} {p75} {p95}" ,
#       all_categorical() ~ "{n} / {N} ({p}%)"
#     )
#   ) %>%
#   # add statistic labels
#   gtsummary::add_stat_label() %>%
#   # bold variable labels, italicize levels
#   gtsummary::bold_labels() %>%
#   gtsummary::italicize_levels() 


```



## Univariate summary

### Continous variables

#### Age

```{r}
#library(patchwork)
#source(here::here("R", "plot_hist.R"))
#ida_plot_hist(crash2, age, bin_width = 1)
```


```{r, fig.width=8, fig.height=3}

x <- as.numeric(crash2$age)

p1 <-
  crash2 %>%
  ggplot2::ggplot(aes(age)) +
  geom_histogram(binwidth = 1, center = 0, alpha = 0.6) +
   geom_rug() +
    scale_x_continuous(limit=c(min(x), max(x)), 
                     breaks=round(fivenum(x),1)) +  
   ggplot2::theme_minimal() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(colour = "grey", size = 1),
      panel.grid.minor = element_blank(),
      axis.title = element_blank(),
      axis.text.y = element_blank()
   )

p2 <- 
  crash2 %>%
  ggplot(aes(x = age, y = 0)) +
  geom_boxplot(outlier.shape = NA, width = 0.1) + 
    scale_x_continuous(limit=c(min(x), max(x)), 
                     breaks=round(fivenum(x),1)) +  
    ggplot2::theme_minimal() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank(),
      axis.title.y = element_blank(),
      axis.text.y = element_blank()
   )

p3 <- 
  crash2 %>%
  ggplot(aes(x = age, y = 0)) +
  geom_jitter(width = 0.1, height = 0.1, alpha = 0.2) +
    geom_rug(sides="b") +
    scale_x_continuous(limit=c(min(x), max(x)), 
                     breaks=round(fivenum(x),1)) +  
  ggplot2::theme_minimal() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank(),
      axis.title = element_blank(),
      axis.text = element_blank()
   )


layout <- c(
  patchwork::area(1, 1, 1, 3),
  patchwork::area(2, 1, 5, 3),
  patchwork::area(6, 1, 6, 3)
)

gg <- p3 / p1 / p2 +
  patchwork::plot_layout(design = layout)

gg

# p2 <- data %>%
#   ggplot(aes(x = {{var}}, y = factor(1))) +
#   geom_jitter(alpha = 0.2, colour = "red") +
#   #  geom_boxplot() +
#   #    scale_x_continuous(
#   #      limits = c(breaks$min, breaks$max)
#   #      ,
#   #      breaks = c(breaks$min, breaks$mean, breaks$median, breaks$max),
#   #      guide = guide_axis(n.dodge = 2)
#   #    ) +
#   ggplot2::theme_minimal()
# 

# 
# layout <- c(
#   patchwork::area(1, 1, 1, 3),
#   patchwork::area(2, 1, 5, 3),
#   patchwork::area(6, 1, 6, 3)
# )
# 
# gg <- p2 / p1 / p3 +
#   patchwork::plot_layout(design = layout)

# #  +
# #    theme(
# #      panel.grid.major = element_blank(),
# #      panel.grid.minor = element_blank(),
# #      axis.title = element_blank(),
# #      axis.text = element_blank()
# #   )
# 
# 

```

```{r}
x <- as.numeric(crash2$sbp)

p1 <-
  crash2 %>%
  ggplot2::ggplot(aes(sbp)) +
  geom_histogram(binwidth = 1, center = 0, fill = "red", alpha = 0.8) +
   geom_rug() +
    scale_x_continuous(
      limit=c(min(x), max(x)), 
                     breaks=round(fivenum(x),1)) + 
   ggplot2::theme_minimal()

p2 <- 
  crash2 %>%
  ggplot(aes(x = sbp, y = 0)) +
  geom_boxplot(outlier.shape = NA, width = 0.1) + 
  geom_jitter(aes(x = sbp, y = 0.2), width = 0.1, height = 0.1, alpha = 0.2, colour = "red") +
    scale_x_continuous(
      limit=c(min(x), max(x)), 
                     breaks=round(fivenum(x),1)) + 
  ggplot2::theme_minimal()

p1 / p2


```





## Session info

```{r}
sessionInfo()
```


